--- 
config:
  image: dockerniu/config-microservice
  hostname: configServer
  links:
    - discovery
  ports:
    - "8888:8888"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
discovery:
  image: dockerniu/discovery-microservice
  hostname: discovery
  ports:
    - "8761:8761"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
gateway:
  image: dockerniu/api-gateway-microservice
  hostname: gateway
  links:
    - discovery
    - config
    - user
    - rating
    - movie
  ports:
    - "10000:10000"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
movie:
  hostname: movie
  image: dockerniu/movie-microservice
  links:
    - discovery
    - config
  ports:
    - "9006:9006"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
moviesui:
  image: dockerniu/ui-search
  links:
    - discovery
    - config
  ports:
    - "1111:1111"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
rating:
  hostname: rating
  image: dockerniu/rating-microservice
  links:
    - discovery
    - config
  ports:
    - "9004:9004"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
user:
  hostname: user
  image: dockerniu/user-microservice
  links:
    - discovery
    - config
  environment:
    - SPRING_PROFILES_ACTIVE=docker